### ISSUE TITLE
GDBrowser only works on the index.js directory

### ISSUE THREAD

**Issue by Eleiber** [GDColon/GDBrowser#165]
Hi! I was trying to run GDBrowser from a different folder than the one where the index.js file is. Because of this:
`ubuntu@someserver:~/GDBrowser$ node index.js` works for me, but
`ubuntu@someserver:/$ node /home/ubuntu/GDBrowser/index.js` doesn't work:
```js
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open './icons/colors.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/home/ubuntu/GDBrowser/index.js:48:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```
I think the relative paths should be based on the file location instead of the current working directory. I'm not expert on NodeJS but as I found on [this question](https://stackoverflow.com/questions/44600943/fs-readfilesync-is-not-file-relative-node-js/44601028), looks like this should do the trick:
```js
const path = require("path");
const file = fs.readFileSync(path.resolve(__dirname, "./some/folder/file.json"));
```

**Comment by GDColon** [comment]
Yeah tbh it's better to just run it from the actual directory, would rather use require() as opposed to some weird path trickery
